# ðŸ”´ Task 13: Data manipulation with Pandas (indexing, selection, grouping)
#### Submitted by : Malaika Ahmed

## 1. Load a DataFrame from a CSV file. Display the first and last five rows of the DataFrame.

In [2]:
import pandas as pd
import numpy as np

pd.read_csv('Desktop/TASK#13_BWF_Malaika/Fortune 500 2017 - Fortune 500.csv')

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Michaels Cos.,http://www.michaels.com,31000,Retailing,Specialty Retailers: Other,"Irving, TX",8000 Bent Branch Dr.,Irving,TX,...,Chairman & Chief Executive Officer,"8000 Bent Branch Dr., Irving, TX 75063",MIK,"The Michaels Companies, Inc.",5197,5.8,378.2,4.2,2148,-1698.0
496,497,Toll Brothers,http://www.tollbrothers.com,4200,Engineering & Construction,Homebuilders,"Horsham, PA",250 Gibraltar Rd.,Horsham,PA,...,Chief Executive Officer & Director,"250 Gibraltar Rd., Horsham, PA 19044",TOL,"Toll Brothers, Inc.",5170,23.9,382.1,5.2,9737,4229.0
497,498,Yahoo,http://www.yahoo.com,8500,Technology,Internet Services and Retailing,"Sunnyvale, CA",701 First Ave.,Sunnyvale,CA,...,"President, Chief Executive Officer & Director","701 First Ave., Sunnyvale, CA 94089",YHOO,Yahoo! Inc.,5169,4.0,-214.3,5.2,48083,31049.0
498,499,Vistra Energy,http://www.vistraenergy.com,4431,Energy,Energy,"Dallas, TX",1601 Bryan St.,Dallas,TX,...,"President, Chief Executive Officer & Director","1601 Bryan St., Dallas, TX 75201",VST,Vistra Energy Corp.,5164,4.0,-214.3,5.2,15167,6597.0
499,500,ABM Industries,http://www.abm.com,110000,Business Services,Diversified Outsourcing Services,"New York, NY",1 Liberty Plaza,New York,NY,...,"President, Chief Executive Officer & Director","1 Liberty Plaza, New York, NY 10006",ABM,ABM Industries Incorporated,5145,-2.8,57.2,-25,2281,974.0

In [3]:
company=pd.read_csv('Desktop/TASK#13_BWF_Malaika/Fortune 500 2017 - Fortune 500.csv')

In [4]:
company.head()

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

In [5]:
company.tail()

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
495,496,Michaels Cos.,http://www.michaels.com,31000,Retailing,Specialty Retailers: Other,"Irving, TX",8000 Bent Branch Dr.,Irving,TX,...,Chairman & Chief Executive Officer,"8000 Bent Branch Dr., Irving, TX 75063",MIK,"The Michaels Companies, Inc.",5197,5.8,378.2,4.2,2148,-1698.0
496,497,Toll Brothers,http://www.tollbrothers.com,4200,Engineering & Construction,Homebuilders,"Horsham, PA",250 Gibraltar Rd.,Horsham,PA,...,Chief Executive Officer & Director,"250 Gibraltar Rd., Horsham, PA 19044",TOL,"Toll Brothers, Inc.",5170,23.9,382.1,5.2,9737,4229.0
497,498,Yahoo,http://www.yahoo.com,8500,Technology,Internet Services and Retailing,"Sunnyvale, CA",701 First Ave.,Sunnyvale,CA,...,"President, Chief Executive Officer & Director","701 First Ave., Sunnyvale, CA 94089",YHOO,Yahoo! Inc.,5169,4.0,-214.3,5.2,48083,31049.0
498,499,Vistra Energy,http://www.vistraenergy.com,4431,Energy,Energy,"Dallas, TX",1601 Bryan St.,Dallas,TX,...,"President, Chief Executive Officer & Director","1601 Bryan St., Dallas, TX 75201",VST,Vistra Energy Corp.,5164,4.0,-214.3,5.2,15167,6597.0
499,500,ABM Industries,http://www.abm.com,110000,Business Services,Diversified Outsourcing Services,"New York, NY",1 Liberty Plaza,New York,NY,...,"President, Chief Executive Officer & Director","1 Liberty Plaza, New York, NY 10006",ABM,ABM Industries Incorporated,5145,-2.8,57.2,-25,2281,974.0

## 2.Set a specific column as the index of the DataFrame.

In [6]:
index=company['Rank']
company.index=index
company

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Rank,,,,,,,,,,,,,,,,,,,,,
1,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
2,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
3,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
4,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
5,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,496,Michaels Cos.,http://www.michaels.com,31000,Retailing,Specialty Retailers: Other,"Irving, TX",8000 Bent Branch Dr.,Irving,TX,...,Chairman & Chief Executive Officer,"8000 Bent Branch Dr., Irving, TX 75063",MIK,"The Michaels Companies, Inc.",5197,5.8,378.2,4.2,2148,-1698.0
497,497,Toll Brothers,http://www.tollbrothers.com,4200,Engineering & Construction,Homebuilders,"Horsham, PA",250 Gibraltar Rd.,Horsham,PA,...,Chief Executive Officer & Director,"250 Gibraltar Rd., Horsham, PA 19044",TOL,"Toll Brothers, Inc.",5170,23.9,382.1,5.2,9737,4229.0
498,498,Yahoo,http://www.yahoo.com,8500,Technology,Internet Services and Retailing,"Sunnyvale, CA",701 First Ave.,Sunnyvale,CA,...,"President, Chief Executive Officer & Director","701 First Ave., Sunnyvale, CA 94089",YHOO,Yahoo! Inc.,5169,4.0,-214.3,5.2,48083,31049.0
499,499,Vistra Energy,http://www.vistraenergy.com,4431,Energy,Energy,"Dallas, TX",1601 Bryan St.,Dallas,TX,...,"President, Chief Executive Officer & Director","1601 Bryan St., Dallas, TX 75201",VST,Vistra Energy Corp.,5164,4.0,-214.3,5.2,15167,6597.0
500,500,ABM Industries,http://www.abm.com,110000,Business Services,Diversified Outsourcing Services,"New York, NY",1 Liberty Plaza,New York,NY,...,"President, Chief Executive Officer & Director","1 Liberty Plaza, New York, NY 10006",ABM,ABM Industries Incorporated,5145,-2.8,57.2,-25,2281,974.0

## 3.Select a specific column and display its values.

In [7]:
company['Title']

Rank
1                 Walmart
2      Berkshire Hathaway
3                   Apple
4             Exxon Mobil
5                McKesson
              ...
496         Michaels Cos.
497         Toll Brothers
498                 Yahoo
499         Vistra Energy
500        ABM Industries
Name: Title, Length: 500, dtype: object

## 4.Select multiple columns and display the resulting DataFrame.

In [8]:
company[['Title','Industry','Sector']]

,Title,Industry,Sector
Rank,,,
1,Walmart,General Merchandisers,Retailing
2,Berkshire Hathaway,Insurance: Property and Casualty (Stock),Financials
3,Apple,"Computers, Office Equipment",Technology
4,Exxon Mobil,Petroleum Refining,Energy
5,McKesson,Wholesalers: Health Care,Wholesalers
...,...,...,...
496,Michaels Cos.,Specialty Retailers: Other,Retailing
497,Toll Brothers,Homebuilders,Engineering & Construction
498,Yahoo,Internet Services and Retailing,Technology
499,Vistra Energy,Energy,Energy
500,ABM Industries,Diversified Outsourcing Services,Business Services

## 5.Select a subset of rows using the .loc method.

In [9]:
company.loc[2]

Rank                                                  2
Title                                Berkshire Hathaway
Website                http://www.berkshirehathaway.com
Employees                                        367700
Sector                                       Financials
Industry       Insurance: Property and Casualty (Stock)
Hqlocation                                    Omaha, NE
Hqaddr                                  3555 Farnam St.
Hqcity                                            Omaha
Hqstate                                              NE
Hqzip                                             68131
Hqtel                                      402-346-1400
Ceo                                   Warren E. Buffett
Ceo-title            Chairman & Chief Executive Officer
Address                3555 Farnam St., Omaha, NE 68131
Ticker                                             BRKA
Fullname                        Berkshire Hathaway Inc.
Revenues                                         223604
Revchange                                           6.1
Profits                                         24074.0
Prftchange                                            0
Assets                                           620854
Totshequity                                    283001.0
Name: 2, dtype: object

## 6.Select a subset of rows and columns using the .iloc method.

In [10]:
company.iloc[[0,2,4]]

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Rank,,,,,,,,,,,,,,,,,,,,,
1,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
3,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
5,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

## 7.Filter rows based on a condition.

In [11]:
filtered_rows=company[company['Employees'] < 100]
print(filtered_rows)

      Rank                   Title               Website  Employees  \
Rank
395    395  A-Mark Precious Metals  http://www.amark.com         83

         Sector       Industry        Hqlocation                  Hqaddr  \
Rank
395   Materials  Miscellaneous  Santa Monica, CA  429 Santa Monica Blvd.

            Hqcity Hqstate  ...                           Ceo-title  \
Rank                        ...
395   Santa Monica      CA  ...  Chief Executive Officer & Director

                                             Address Ticker  \
Rank
395   429 Santa Monica Blvd., Santa Monica, CA 90401   AMRK

                          Fullname Revenues Revchange Profits  Prftchange  \
Rank
395   A-Mark Precious Metals, Inc.     6784      11.8     9.3        31.5

      Assets  Totshequity
Rank
395      437         63.0

[1 rows x 23 columns]

## 8.Group the DataFrame by a specific column and calculate the mean of each group.

In [12]:
groupby_data=company.groupby('Sector')
print(groupby_data)

mean=groupby_data.mean(numeric_only=True) 
print(mean)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000260221CE990>
                                     Rank      Employees         Hqzip  \
Sector
Aerospace & Defense            201.333333   71986.666667  25020.500000
Apparel                        291.200000   50930.000000  34311.200000
Business Services              329.200000   42252.500000  45069.200000
Chemicals                      284.714286   26064.714286  42833.142857
Energy                         249.421053   15254.578947  59845.789474
Engineering & Construction     331.153846   25314.615385  51807.692308
Financials                     247.797619   37642.833333  34289.547619
Food & Drug Stores              84.857143  198585.000000  53398.857143
Food, Beverages & Tobacco      237.416667   41679.541667  44271.833333
Health Care                    182.947368   61616.394737  37741.552632
Hotels, Restaurants & Leisure  286.000000  183874.200000  53492.200000
Household Products             296.333333   40278.666667  36486.500000
Industrials                    237.157895   64436.631579  44082.684211
Materials                      343.368421   20280.000000  51266.789474
Media                          276.727273   34431.454545  42882.636364
Motor Vehicles & Parts         232.555556   91025.000000  53697.555556
Retailing                      242.851064  123827.382979  46602.000000
Technology                     244.744186   70915.069767  68534.069767
Telecommunications             207.900000   79324.900000  42375.700000
Transportation                 238.588235   78305.588235  50787.705882
Wholesalers                    260.931034   21753.172414  49092.620690

                                   Revenues  Revchange      Profits  \
Sector
Aerospace & Defense            28191.833333  -3.208333  2093.308333
Apparel                        13250.800000   1.940000  1263.700000
Business Services               9734.250000   5.590000  1155.355000
Chemicals                      13476.214286   2.228571  1137.021429
Energy                         20638.894737  -7.792982     6.501754
Engineering & Construction      9590.923077  13.369231   390.169231
Financials                     24614.369048   2.573810  2719.776190
Food & Drug Stores             55669.428571  22.271429  1217.428571
Food, Beverages & Tobacco      19700.250000   5.404167  2346.183333
Health Care                    34694.447368  10.223684  2773.260526
Hotels, Restaurants & Leisure  12118.900000  -1.950000  1451.060000
Household Products             15070.500000   8.775000  1650.308333
Industrials                    22018.894737  -5.036842  1727.689474
Materials                       8934.473684   8.042105   272.468421
Media                          16433.363636  -1.145455  1821.336364
Motor Vehicles & Parts         43607.333333  11.300000  1919.533333
Retailing                      29431.510638   2.485106   991.785106
Technology                     29246.255814   7.162791  4137.241860
Telecommunications             45997.800000  28.380000  4127.280000
Transportation                 20866.647059   5.476471  1670.294118
Wholesalers                    27566.068966   3.834483   391.279310

                                      Assets   Totshequity
Sector
Aerospace & Defense             31897.666667   6425.750000
Apparel                         11064.800000   5394.400000
Business Services               19626.100000   5044.250000
Chemicals                       20151.214286   6185.000000
Energy                          48756.210526  16048.789474
Engineering & Construction       8199.230769   3666.692308
Financials                     319245.095238  31624.828571
Food & Drug Stores              24630.714286   7861.142857
Food, Beverages & Tobacco       29059.750000   9035.958333
Health Care                     42078.894737  14021.500000
Hotels, Restaurants & Leisure   16795.400000   2672.000000
Household Products              23179.083333   7188.166667
Industrials                     40117.684211   9844.773684
Materials                       10833.263158   3034.368421
Media                           30876.272727   9792.090909
Motor Vehicles & Parts          59443.111111  10440.366667
Retailing                       14473.148936   3963.212766
Technology                      48380.325581  21049.441860
Telecommunications             114922.700000  28014.700000
Transportation                  25922.000000   6442.000000
Wholesalers                      9362.586207   2222.755172

## 9. Group the DataFrame by multiple columns and calculate the sum of each group.

In [16]:
groupby_data=company.groupby(['Sector','Industry'])
print(groupby_data)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000260221D33D0>

In [17]:
sum=groupby_data.sum(numeric_only=True) 
print(sum)

                                                                   Rank  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          2416
Apparel             Apparel                                        1456
Business Services   Advertising, Marketing                          524
                    Diversified Outsourcing Services                932
                    Financial Data Services                        3047
...                                                                 ...
Transportation      Trucking, Truck Leasing                         801
Wholesalers         Wholesalers: Diversified                       3415
                    Wholesalers: Electronics and Office Equipment  1850
                    Wholesalers: Food and Grocery                  1274
                    Wholesalers: Health Care                       1028

                                                                   Employees  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                             863840
Apparel             Apparel                                           254650
Business Services   Advertising, Marketing                            128300
                    Diversified Outsourcing Services                  384250
                    Financial Data Services                           193900
...                                                                      ...
Transportation      Trucking, Truck Leasing                            56690
Wholesalers         Wholesalers: Diversified                          175170
                    Wholesalers: Electronics and Office Equipment     177330
                    Wholesalers: Food and Grocery                     118642
                    Wholesalers: Health Care                          159700

                                                                    Hqzip  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          300246
Apparel             Apparel                                        171556
Business Services   Advertising, Marketing                          20044
                    Diversified Outsourcing Services                36181
                    Financial Data Services                        480880
...                                                                   ...
Transportation      Trucking, Truck Leasing                        105923
Wholesalers         Wholesalers: Diversified                       372091
                    Wholesalers: Electronics and Office Equipment  498768
                    Wholesalers: Food and Grocery                  306636
                    Wholesalers: Health Care                       246191

                                                                   Revenues  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                            338302
Apparel             Apparel                                           66254
Business Services   Advertising, Marketing                            23264
                    Diversified Outsourcing Services                  31229
                    Financial Data Services                           81252
...                                                                     ...
Transportation      Trucking, Truck Leasing                           13343
Wholesalers         Wholesalers: Diversified                          85759
                    Wholesalers: Electronics and Office Equipment    108821
                    Wholesalers: Food and Grocery                    117103
                    Wholesalers: Health Care                         487733

                                                                   Revchange  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                              -38.5
Apparel             Apparel                                              9.7
Business Services   Advertising, Marketing                               5.0
                    Diversified Outsourcing Services                    -0.5
                    Financial Data Services                             99.8
...                                                                      ...
Transportation      Trucking, Truck Leasing                              9.2
Wholesalers         Wholesalers: Diversified                           -18.4
                    Wholesalers: Electronics and Office Equipment       18.9
                    Wholesalers: Food and Grocery                       42.6
                    Wholesalers: Health Care                            68.1

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          25119.7
Apparel             Apparel                                         6318.5
Business Services   Advertising, Marketing                          1757.1
                    Diversified Outsourcing Services                1837.5
                    Financial Data Services                        16244.0
...                                                                    ...
Transportation      Trucking, Truck Leasing                          694.6
Wholesalers         Wholesalers: Diversified                        2238.5
                    Wholesalers: Electronics and Office Equipment   1728.4
                    Wholesalers: Food and Grocery                   1464.5
                    Wholesalers: Health Care                        5915.7

                                                                   Assets  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          382772
Apparel             Apparel                                         55324
Business Services   Advertising, Marketing                          35650
                    Diversified Outsourcing Services                56533
                    Financial Data Services                        235482
...                                                                   ...
Transportation      Trucking, Truck Leasing                         14732
Wholesalers         Wholesalers: Diversified                        51726
                    Wholesalers: Electronics and Office Equipment   47078
                    Wholesalers: Food and Grocery                   35401
                    Wholesalers: Health Care                       137310

                                                                   Totshequity
Sector              Industry
Aerospace & Defense Aerospace and Defense                              77109.0
Apparel             Apparel                                            26972.0
Business Services   Advertising, Marketing                              4179.0
                    Diversified Outsourcing Services                    7617.0
                    Financial Data Services                            69992.0
...                                                                        ...
Transportation      Trucking, Truck Leasing                             3466.0
Wholesalers         Wholesalers: Diversified                           15925.9
                    Wholesalers: Electronics and Office Equipment      16036.0
                    Wholesalers: Food and Grocery                       9696.0
                    Wholesalers: Health Care                           22802.0

[76 rows x 8 columns]

## 10. Use the agg method to apply multiple aggregation functions to grouped data.

In [25]:
groupby_data = company.groupby('Sector')
agg_data = groupby_data.agg({
    'Employees': ['mean', 'sum', 'max', 'min'],
    'Revenues': ['mean', 'sum', 'max', 'min']
})

print(agg_data)

                                   Employees                           \
                                        mean      sum      max    min
Sector
Aerospace & Defense             71986.666667   863840   201600  14400
Apparel                         50930.000000   254650    70700  20500
Business Services               42252.500000   845050   217250   7500
Chemicals                       26064.714286   364906    56000   6400
Energy                          15254.578947   869511    72700   1326
Engineering & Construction      25314.615385   329090    87000   3055
Financials                      37642.833333  3161998   367700    220
Food & Drug Stores             198585.000000  1390095   443000  38000
Food, Beverages & Tobacco       41679.541667  1000309   264000   5525
Health Care                     61616.394737  2341423   230000   7132
Hotels, Restaurants & Leisure  183874.200000  1838742   420000  37800
Household Products              40278.666667   483344   105000   8000
Industrials                     64436.631579  1224296   295000  11300
Materials                       20280.000000   385320    55000     83
Media                           34431.454545   378746   195000   3626
Motor Vehicles & Parts          91025.000000   819225   225000  24900
Retailing                      123827.382979  5819887  2300000   6600
Technology                      70915.069767  3049348   414400   3850
Telecommunications              79324.900000   793249   268540   4507
Transportation                  78305.588235  1331195   335767   6000
Wholesalers                     21753.172414   630842   110000   1770

                                   Revenues
                                       mean      sum     max    min
Sector
Aerospace & Defense            28191.833333   338302   94571   5259
Apparel                        13250.800000    66254   32376   6063
Business Services               9734.250000   194685   19654   5145
Chemicals                      13476.214286   188667   48158   5389
Energy                         20638.894737  1176417  205004   5164
Engineering & Construction      9590.923077   124682   19037   5170
Financials                     24614.369048  2067607  223604   5398
Food & Drug Stores             55669.428571   389686  117351  15724
Food, Beverages & Tobacco      19700.250000   472806   62799   5379
Health Care                    34694.447368  1318389  184840   5733
Hotels, Restaurants & Leisure  12118.900000   121189   24622   5599
Household Products             15070.500000   180846   71726   5457
Industrials                    22018.894737   418359  126661   5841
Materials                       8934.473684   169755   21079   5677
Media                          16433.363636   180767   55632   5276
Motor Vehicles & Parts         43607.333333   392466  166380   5826
Retailing                      29431.510638  1383281  485873   5197
Technology                     29246.255814  1257589  215639   5169
Telecommunications             45997.800000   459978  163786   5387
Transportation                 20866.647059   354733   60906   5931
Wholesalers                    27566.068966   799416  192487   5314

## 11. Calculate the size of each group.

In [18]:
groupby_data=company.groupby('Sector')
print(groupby_data)
Sector=groupby_data.size()
print(Sector)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000260221D5E10>
Sector
Aerospace & Defense              12
Apparel                           5
Business Services                20
Chemicals                        14
Energy                           57
Engineering & Construction       13
Financials                       84
Food & Drug Stores                7
Food, Beverages & Tobacco        24
Health Care                      38
Hotels, Restaurants & Leisure    10
Household Products               12
Industrials                      19
Materials                        19
Media                            11
Motor Vehicles & Parts            9
Retailing                        47
Technology                       43
Telecommunications               10
Transportation                   17
Wholesalers                      29
dtype: int64

## 12 Select rows based on multiple conditions.

In [19]:
company[ (company['Employees'] < 100) & (company['Sector'] == 'Materials') ]

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Rank,,,,,,,,,,,,,,,,,,,,,
395,395,A-Mark Precious Metals,http://www.amark.com,83,Materials,Miscellaneous,"Santa Monica, CA",429 Santa Monica Blvd.,Santa Monica,CA,...,Chief Executive Officer & Director,"429 Santa Monica Blvd., Santa Monica, CA 90401",AMRK,"A-Mark Precious Metals, Inc.",6784,11.8,9.3,31.5,437,63.0

## 13.Use the query method to filter rows.

In [20]:
company.query('Employees <500  and Sector == "Financials"')

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Rank,,,,,,,,,,,,,,,,,,,,,
472,472,Host Hotels & Resorts,http://www.hosthotels.com,220,Financials,Real Estate,"Bethesda, MD",6903 Rockledge Dr.,Bethesda,MD,...,"President, Chief Executive Officer & Director","6903 Rockledge Dr., Bethesda, MD 20817",HST,"Host Hotels & Resorts, Inc.",5488,1.9,762.0,36.6,11408,6994.0

## 14.Use isin to filter rows based on a list of values.

In [21]:
company[company['Sector'].isin(['Materials','Energy'])]

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Rank,,,,,,,,,,,,,,,,,,,,,
4,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
19,19,Chevron,http://www.chevron.com,55200,Energy,Petroleum Refining,"San Ramon, CA",6001 Bollinger Canyon Rd.,San Ramon,CA,...,Chairman & Chief Executive Officer,"6001 Bollinger Canyon Rd., San Ramon, CA 94583",CVX,Chevron Corporation,107567,-18.0,-497.0,-110.8,260078,145556.0
34,34,Phillips 66,http://www.phillips66.com,14800,Energy,Petroleum Refining,"Houston, TX",2331 CityWest Blvd.,Houston,TX,...,Chairman & Chief Executive Officer,"2331 CityWest Blvd., Houston, TX 77042",PSX,Phillips 66,72396,-16.9,1555.0,-63.2,51653,22390.0
37,37,Valero Energy,http://www.valero.com,9996,Energy,Petroleum Refining,"San Antonio, TX",1 Valero Way,San Antonio,TX,...,"Chairman, President & Chief Executive Officer","1 Valero Way, San Antonio, TX 78249",VLO,Valero Energy Corporation,70166,-14.2,2289.0,-42.6,46173,20024.0
51,51,Marathon Petroleum,http://www.marathonpetroleum.com,44460,Energy,Petroleum Refining,"Findlay, OH",539 S. Main St.,Findlay,OH,...,"Chairman, President & Chief Executive Officer","539 S. Main St., Findlay, OH 45840",MPC,Marathon Petroleum Corporation,55858,-13.5,1174.0,-58.8,44413,13557.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,457,UGI,http://www.ugicorp.com,13105,Energy,Energy,"King of Prussia, PA",460 N. Gulph Rd.,King of Prussia,PA,...,"President, Chief Executive Officer & Director","460 N. Gulph Rd., King of Prussia, PA 19406",UGI,UGI Corporation,5686,-15.0,364.7,29.8,10847,2851.0
458,458,Owens Corning,http://www.owenscorning.com,16000,Materials,"Building Materials, Glass","Toledo, OH",1 Owens Corning Pkwy.,Toledo,OH,...,"Chairman, President & Chief Executive Officer","1 Owens Corning Pkwy., Toledo, OH 43659",OC,Owens Corning,5677,6.1,393.0,19.1,7741,3849.0
480,480,Delek US Holdings,http://www.delekus.com,1326,Energy,Petroleum Refining,"Brentwood, TN",7102 Commerce Way,Brentwood,TN,...,"Chairman, President & Chief Executive Officer","7102 Commerce Way, Brentwood, TN 37027",DK,"Delek US Holdings, Inc.",5414,-6.0,-153.7,-892.3,2985,992.0
488,488,Apache,http://www.apachecorp.com,3727,Energy,"Mining, Crude-Oil Production","Houston, TX",2000 Post Oak Blvd.,Houston,TX,...,"President, Chief Executive Officer & Director","2000 Post Oak Blvd., Houston, TX 77056",APA,Apache Corporation,5354,-19.5,-1405.0,82.5,22519,6238.0
499,499,Vistra Energy,http://www.vistraenergy.com,4431,Energy,Energy,"Dallas, TX",1601 Bryan St.,Dallas,TX,...,"President, Chief Executive Officer & Director","1601 Bryan St., Dallas, TX 75201",VST,Vistra Energy Corp.,5164,4.0,-214.3,5.2,15167,6597.0

## 15.Select specific columns and rename them.

In [22]:
rename=company[['Title','Industry','Sector']]
rename.rename(columns={'Title':'Company Name','Industry':'Industry Name','Sector':'Sector Name'})

,Company Name,Industry Name,Sector Name
Rank,,,
1,Walmart,General Merchandisers,Retailing
2,Berkshire Hathaway,Insurance: Property and Casualty (Stock),Financials
3,Apple,"Computers, Office Equipment",Technology
4,Exxon Mobil,Petroleum Refining,Energy
5,McKesson,Wholesalers: Health Care,Wholesalers
...,...,...,...
496,Michaels Cos.,Specialty Retailers: Other,Retailing
497,Toll Brothers,Homebuilders,Engineering & Construction
498,Yahoo,Internet Services and Retailing,Technology
499,Vistra Energy,Energy,Energy
500,ABM Industries,Diversified Outsourcing Services,Business Services